version: 2
jobs:
  build:
    docker:
      - image: google/cloud-sdk
    steps:
      - run: apt-get install -qqy build-essential
      - setup_remote_docker
      - checkout
      - run: make docker-test
      - run: make docker
      - deploy:
          command: |
            if [[ "${CIRCLE_BRANCH}" == "master" && -z "${CIRCLE_PR_REPONAME}" ]]; then
              git config --global user.email "ci@gochain.io"
              git config --global user.name "CI"
              git branch --set-upstream-to=origin/${CIRCLE_BRANCH} ${CIRCLE_BRANCH}
              echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
              echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
              gcloud --quiet auth configure-docker
              make release
            fi
